
workflows:
  android-only-release:
    name: Ravn AI Android Only Release
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
